{% set name = "csvw" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/csvw-{{ version }}.tar.gz
  sha256: ae4ea6735f27bb6c20b4f5cac197f24b0130a631550c7fc0b09fd5f6a8720d4e

build:
  entry_points:
    - csvwdescribe = csvw.__main__:csvwdescribe
    - csvw2json = csvw.__main__:csvw2json
    - csvw2datasette = csvw.__main__:csvw2datasette
    - csvwvalidate = csvw.__main__:csvwvalidate
    - csvw2sqlite = csvw.__main__:csvw2sqlite
    - csvw2markdown = csvw.__main__:csvw2markdown
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - termcolor
    - python >={{ python_min }}
    - attrs >=18.1
    - isodate
    - python-dateutil
    - rfc3986 <2
    - uritemplate >=3.0.0
    - babel
    - requests
    - language-tags
    - rdflib
    - colorama
    - jsonschema

test:
  imports:
    - csvw
  commands:
    - pip check
    # This would require the frictionless extra
    # - csvwdescribe --help
    - csvw2json --help
    - csvw2datasette --help
    - csvwvalidate --help
    - csvw2sqlite --help
    - csvw2markdown --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cldf/csvw
  summary: Python library to work with CSVW described tabular data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
